/***************************************
 * Decompiled and Edited by SyndiShanX
 * Script: maps\mp\mp_ca_rumble_fx.gsc
***************************************/

main() {
  level._effect["vfx_insects_dense"] = loadfx("vfx/moments/mp_ca_rumble/vfx_insects_dense");
  level._effect["vfx_micro_particulates_01"] = loadfx("vfx/moments/mp_ca_rumble/vfx_micro_particulates_01");
  level._effect["vfx_1_leafs_burst"] = loadfx("vfx/moments/mp_ca_rumble/vfx_1_leafs_burst");
  level._effect["vfx_1_groundmist_base"] = loadfx("vfx/moments/mp_ca_rumble/vfx_1_groundmist_base");
  level._effect["vfx_mist_cloud"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mist_cloud");
  level._effect["vfx_shark_fire"] = loadfx("vfx/moments/mp_ca_rumble/vfx_shark_fire");
  level._effect["vfx_vertical_missile_launch"] = loadfx("vfx/moments/mp_ca_rumble/vfx_vertical_missile_launch");
  level._effect["vfx_missile_boat"] = loadfx("vfx/moments/mp_ca_rumble/vfx_missile_boat");
  level._effect["vfx_battleship_firing_timing"] = loadfx("vfx/moments/mp_ca_rumble/vfx_battleship_firing_timing");
  level._effect["vfx_impact_water_timing"] = loadfx("vfx/moments/mp_ca_rumble/vfx_impact_water_timing");
  level._effect["vfx_impact_water_close_timing"] = loadfx("vfx/moments/mp_ca_rumble/vfx_impact_water_close_timing");
  level._effect["vfx_vista_smoke"] = loadfx("vfx/moments/mp_ca_rumble/vfx_vista_smoke");
  level._effect["vfx_vista_carrier_fire"] = loadfx("vfx/moments/mp_ca_rumble/vfx_vista_carrier_fire");
  level._effect["vfx_vista_distant_flak"] = loadfx("vfx/moments/mp_ca_rumble/vfx_vista_distant_flak");
  level._effect["vfx_battlesmoke"] = loadfx("vfx/moments/mp_ca_rumble/vfx_battlesmoke");
  level._effect["vfx_water_fountain"] = loadfx("vfx/moments/mp_ca_rumble/vfx_water_fountain");
  level._effect["vfx_vista_distant_flak_runner"] = loadfx("vfx/moments/mp_ca_rumble/vfx_vista_distant_flak_runner");
  level._effect["vfx_lightpost_atmosphere"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost_atmosphere");
  level._effect["vfx_lightpost_bugs"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost_bugs");
  level._effect["vfx_lightpost_cone"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost_cone");
  level._effect["vfx_lightpost2_cone"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost2_cone");
  level._effect["vfx_lightpost3_cone"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost3_cone");
  level._effect["vfx_lightpost4_cone"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost4_cone");
  level._effect["vfx_lightpost5_cone"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost5_cone");
  level._effect["vfx_lightpost6_cone"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost6_cone");
  level._effect["vfx_big_tank_fish_school"] = loadfx("vfx/moments/mp_ca_rumble/vfx_big_tank_fish_school");
  level._effect["vfx_lightpost_flare"] = loadfx("vfx/moments/mp_ca_rumble/vfx_lightpost_flare");
  level._effect["vfx_mist_02"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mist_02");
  level._effect["vfx_mp_ca_rumble_sun_flare"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mp_ca_rumble_sun_flare");
  level._effect["vfx_pot_lights_blue"] = loadfx("vfx/moments/mp_ca_rumble/vfx_pot_lights_blue");
  level._effect["vfx_pot_lights_warm"] = loadfx("vfx/moments/mp_ca_rumble/vfx_pot_lights_warm");
  level._effect["vfx_pot_lights_aquarium"] = loadfx("vfx/moments/mp_ca_rumble/vfx_pot_lights_aquarium");
  level._effect["vfx_pot_lights_trolley"] = loadfx("vfx/moments/mp_ca_rumble/vfx_pot_lights_trolley");
  level._effect["vfx_watertank_bullet_hit"] = loadfx("vfx/moments/mp_ca_rumble/vfx_watertank_bullet_hit");
  level._effect["vfx_bubble_stream"] = loadfx("vfx/moments/mp_ca_rumble/vfx_bubble_stream");
  level._effect["vfx_fountain_splash_loop"] = loadfx("vfx/moments/mp_ca_rumble/vfx_fountain_splash_loop");
  level._effect["vfx_big_fountain_splash_loop"] = loadfx("vfx/moments/mp_ca_rumble/vfx_big_fountain_splash_loop");
  level._effect["vfx_big_fountain_splash"] = loadfx("vfx/moments/mp_ca_rumble/vfx_big_fountain_splash");
  level._effect["vfx_ocean_splash"] = loadfx("vfx/moments/mp_ca_rumble/vfx_ocean_splash");
  level._effect["vfx_heli_missile_launch"] = loadfx("vfx/moments/mp_ca_rumble/vfx_heli_missile_launch");
  level._effect["vfx_glass_shatter_splash"] = loadfx("vfx/moments/mp_ca_rumble/vfx_glass_shatter_splash");
  level._effect["vfx_glass_ground_splash"] = loadfx("vfx/moments/mp_ca_rumble/vfx_glass_ground_splash");
  level._effect["vfx_mp_ca_rumble_orca_hit"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mp_ca_rumble_orca_hit");
  level._effect["vfx_mp_ca_rumble_orca_death"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mp_ca_rumble_orca_death");
  level._effect["vfx_mp_ca_rumble_shark_death"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mp_ca_rumble_shark_death");
  level._effect["vfx_mp_ca_rumble_shark_hit"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mp_ca_rumble_shark_hit");
  level._effect["vfx_jet_flyby_timing"] = loadfx("vfx/moments/mp_ca_rumble/vfx_jet_flyby_timing");
  level._effect["vfx_heli_timing"] = loadfx("vfx/moments/mp_ca_rumble/vfx_heli_timing");
  level._effect["vfx_fishtank_particulates"] = loadfx("vfx/moments/mp_ca_rumble/vfx_fishtank_particulates");
  level._effect["vfx_pot_lights_restaurant"] = loadfx("vfx/moments/mp_ca_rumble/vfx_pot_lights_restaurant");
  level._effect["vfx_fish_school"] = loadfx("vfx/moments/mp_ca_rumble/vfx_fish_school");
  level._effect["vfx_ground_steam"] = loadfx("vfx/moments/mp_ca_rumble/vfx_ground_steam");
  level._effect["vfx_awning_drip"] = loadfx("vfx/moments/mp_ca_rumble/vfx_awning_drip");
  level._effect["explode"] = loadfx("fx/maps/mp_warhawk/mortar_impact");
  level._effect["random_mortars_impact"] = loadfx("fx/maps/mp_warhawk/mortar_impact");
  level._effect["random_mortars_trail"] = loadfx("vfx/moments/mp_warhawk/mortar_trail");
  level._effect["mortar_impact_04"] = loadfx("vfx/moments/mp_warhawk/mortar_impact_04");
  level._effect["mortar_impact_01"] = loadfx("vfx/moments/mp_warhawk/mortar_impact_01");
  level._effect["mortar_impact_00"] = loadfx("vfx/moments/mp_warhawk/mortar_impact_00");
  level._effect["vfx_metaldetector_explosion"] = loadfx("fx/explosions/wallfan_explosion_dmg");
  level._effect["vfx_flatscreen_explosion"] = loadfx("fx/explosions/tv_flatscreen_explosion_quick");
  level._effect["vfx_mist_kickup_timing"] = loadfx("vfx/moments/mp_ca_rumble/vfx_mist_kickup_timing");
}