/****************************************
 * Decompiled and Edited by SyndiShanX
 * Script: maps\mp\mp_favela_iw6_fx.gsc
****************************************/

main() {
  level._effect["vfx_favel_birds_flock_runner"] = loadfx("vfx/moments/mp_favela/vfx_favel_birds_flock_runner");
  level._effect["vfx_scrnfx_waterdrops_favela"] = loadfx("vfx/moments/mp_favela/vfx_scrnfx_waterdrops_favela");
  level._effect["vfx_dust_fall_runner_dark"] = loadfx("vfx/moments/mp_chasm/vfx_dust_fall_runner_dark");
  level._effect["vfx_pipe_drip_ruins"] = loadfx("vfx/moments/mp_battery3/vfx_pipe_drip_ruins");
  level._effect["vfx_leaf_fall_favela"] = loadfx("vfx/moments/mp_favela/vfx_leaf_fall_favela");
  level._effect["vfx_ground_mist_mp_favela"] = loadfx("vfx/moments/mp_favela/vfx_ground_mist_mp_favela");
  level._effect["vfx_dust_drift_outdoor"] = loadfx("vfx/moments/mp_favela/vfx_dust_drift_outdoor");
  level._effect["vfx_dust_drift_indoor_static"] = loadfx("vfx/moments/mp_favela/vfx_dust_drift_indoor_static");
  level._effect["vfx_light_rain_drizzle"] = loadfx("vfx/moments/mp_favela/vfx_light_rain_drizzle");
  level._effect["vfx_cofetti_fall_light"] = loadfx("vfx/moments/mp_favela/vfx_cofetti_fall_light");
  level._effect["vfx_confetti_trash_runner"] = loadfx("vfx/moments/mp_favela/vfx_confetti_trash_runner");
  level._effect["vfx_debris_kickup_favela"] = loadfx("vfx/moments/mp_favela/vfx_debris_kickup_favela");
  level._effect["vfx_grnd_mist_mp_favela"] = loadfx("vfx/moments/mp_favela/vfx_grnd_mist_mp_favela");
  level._effect["vfx_smk_chimney"] = loadfx("vfx/moments/mp_favela/vfx_smk_chimney");
  level._effect["vfx_pipe_pour"] = loadfx("vfx/moments/mp_pirate/vfx_pipe_pour");
  level._effect["vfx_brids_light_favela"] = loadfx("vfx/moments/mp_favela/vfx_brids_light_favela");
  level._effect["vfx_drip_pour_sml"] = loadfx("vfx/moments/mp_favela/vfx_drip_pour_sml");
  level._effect["vfx_dust_motes_turb"] = loadfx("vfx/moments/mp_favela/vfx_dust_motes_turb");
  level._effect["vfx_chick_feath_runner"] = loadfx("vfx/moments/mp_favela/vfx_chick_feath_runner");
  level._effect["vfx_deer_hunt_insects"] = loadfx("vfx/ambient/animals/vfx_deer_hunt_insects");
  level._effect["vfx_dust_motes"] = loadfx("vfx/moments/mp_favela/vfx_dust_motes");
  level._effect["vfx_grnd_mist_inside"] = loadfx("vfx/moments/mp_favela/vfx_grnd_mist_inside");
  level._effect["vfx_building_hole_dust"] = loadfx("vfx/moments/mp_favela/vfx_building_hole_dust");
  level._effect["vfx_debris_fire_tiny"] = loadfx("vfx/moments/mp_chasm/vfx_debris_fire_tiny");
  level._effect["vfx_debris_fire_sm"] = loadfx("vfx/moments/mp_chasm/vfx_debris_fire_sm");
  level._effect["vfx_burnt_car_smold"] = loadfx("vfx/moments/mp_favela/vfx_burnt_car_smold");
  level._effect["vfx_trash_fly_runner"] = loadfx("vfx/moments/mp_favela/vfx_trash_fly_runner");
  level._effect["vfx_trash_fly_child"] = loadfx("vfx/moments/mp_favela/vfx_trash_fly_child");
  level._effect["vfx_birds_flock_large_15sec"] = loadfx("vfx/moments/mp_favela/vfx_birds_flock_large_15sec");
  level._effect["video_soccer_2"] = loadfx("vfx/moments/mp_favela/video_soccer_2");
  level._effect["vfx_fireworks_runner"] = loadfx("vfx/moments/mp_favela/vfx_fireworks_runner");
  level._effect["vfx_mosquitos_swarm"] = loadfx("vfx/moments/mp_favela/vfx_mosquitos_swarm");
  level._effect["ants"] = loadfx("vfx/ambient/animals/ants");
  level._effect["brown_moths"] = loadfx("vfx/ambient/animals/brown_moths");
  level._effect["vfx_butterflies_ruins"] = loadfx("vfx/moments/mp_battery3/vfx_butterflies_ruins");
  level._effect["vfx_bird_flock_large_left"] = loadfx("vfx/ambient/animals/vfx_bird_flock_large_left");
  level._effect["vfx_bird_flock_med"] = loadfx("vfx/ambient/animals/vfx_bird_flock_med");
  level._effect["vfx_ehq_birds_flock_runner"] = loadfx("vfx/ambient/animals/vfx_ehq_birds_flock_runner");
  level._effect["vfx_ehq_birds_flyrunner"] = loadfx("vfx/ambient/animals/vfx_ehq_birds_flyrunner");
  level._effect["vfx_ehq_birds_rand"] = loadfx("vfx/ambient/animals/vfx_ehq_birds_rand");
  level._effect["vfx_mp_gnat_swarm"] = loadfx("vfx/ambient/animals/vfx_mp_gnat_swarm");
  level._effect["vfx_circling_hawk"] = loadfx("vfx/ambient/animals/vfx_circling_hawk");
  level.tv_info = spawnStruct();
  level._effect["tv_explode"] = loadfx("fx/explosions/tv_explosion");
  level._effect["fav_bar_tv"][1] = loadfx("vfx/moments/mp_favela/video_soccer_goal");
  level._effect["fav_bar_tv"][2] = loadfx("vfx/moments/mp_favela/video_soccer_play");
  level._effect["fav_bar_tv"][3] = loadfx("vfx/moments/mp_favela/video_soccer_replay");
  level._effect["fav_bar_tv"][4] = loadfx("vfx/moments/mp_favela/video_brazil_flag");
  level.tv_info.effectlength["fav_bar_tv"][1] = 6.4;
  level.tv_info.effectlength["fav_bar_tv"][2] = 3.2;
  level.tv_info.effectlength["fav_bar_tv"][3] = 14.0;
  level.tv_info.effectlength["fav_bar_tv"][4] = 5.0;
  level.tv_info.destroymodel["fav_bar_tv"] = "tv_tube_screen_des_iw6";
  level._effect["fav_bar_tv_large"][1] = loadfx("vfx/moments/mp_favela/video_soccer_play_flat_tv_scale_2pt5");
  level._effect["fav_bar_tv_large"][2] = loadfx("vfx/moments/mp_favela/video_soccer_play_flat_tv_scale_2pt5");
  level._effect["fav_bar_tv_large"][3] = loadfx("vfx/moments/mp_favela/video_soccer_goal_flat_tv_scale_2pt5");
  level._effect["fav_bar_tv_large"][4] = loadfx("vfx/moments/mp_favela/video_soccer_goal_flat_tv_scale_2pt5");
  level.tv_info.effectlength["fav_bar_tv_large"][1] = 15.0;
  level.tv_info.effectlength["fav_bar_tv_large"][2] = 15.0;
  level.tv_info.effectlength["fav_bar_tv_large"][3] = 9.6;
  level.tv_info.effectlength["fav_bar_tv_large"][4] = 9.6;
  level.tv_info.destroymodel["fav_bar_tv_large"] = "tv_flatscreen_large_scale2pt5_d_on";
}