/*****************************************************
 * Decompiled and Edited by SyndiShanX
 * Script: maps\mp\mp_zerosub_fx.gsc
*****************************************************/

main() {
  level._effect["vfx_button_light_green"] = loadfx("vfx/moments/mp_zerosub/vfx_button_light_green");
  level._effect["vfx_button_light_red"] = loadfx("vfx/moments/mp_zerosub/vfx_button_light_red");
  level._effect["vfx_yeti_glowing_eye"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_glowing_eye");
  level._effect["vfx_light_warning_orange_off3"] = loadfx("vfx/moments/mp_zerosub/vfx_light_warning_orange_off3");
  level._effect["vfx_light_warning_orange_off2"] = loadfx("vfx/moments/mp_zerosub/vfx_light_warning_orange_off2");
  level._effect["vfx_light_warning_orange_off1"] = loadfx("vfx/moments/mp_zerosub/vfx_light_warning_orange_off1");
  level._effect["vfx_single_floodlight"] = loadfx("vfx/moments/mp_zerosub/vfx_single_floodlight");
  level._effect["vfx_light_warning_orange_outdoors"] = loadfx("vfx/moments/mp_zerosub/vfx_light_warning_orange_outdoors");
  level._effect["vfx_floodlight_snow_drift"] = loadfx("vfx/moments/mp_zerosub/vfx_floodlight_snow_drift");
  level._effect["vfx_boiler_smoke"] = loadfx("vfx/moments/mp_zerosub/vfx_boiler_smoke");
  level._effect["vfx_vista_snow_drift"] = loadfx("vfx/moments/mp_zerosub/vfx_vista_snow_drift");
  level._effect["vfx_light_warning_orange"] = loadfx("vfx/moments/mp_zerosub/vfx_light_warning_orange");
  level._effect["vfx_yeti_doorway_window_blizzard"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_doorway_window_blizzard");
  level._effect["vfx_sunflare"] = loadfx("vfx/moments/mp_zerosub/vfx_sunflare");
  level._effect["vfx_dumdum_smokeonthewater"] = loadfx("vfx/moments/mp_zerosub/vfx_dumdum_smokeonthewater");
  level._effect["vfx_snow_drift_icedrift_large"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_icedrift_large");
  level._effect["vfx_light_spotlight_white"] = loadfx("vfx/moments/mp_zerosub/vfx_light_spotlight_white");
  level._effect["vfx_indoors_sparks"] = loadfx("vfx/moments/mp_zerosub/vfx_indoors_sparks");
  level._effect["vfx_snow_drift_flatonly"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_flatonly");
  level._effect["vfx_melt_dripping2"] = loadfx("vfx/moments/mp_zerosub/vfx_melt_dripping2");
  level._effect["vfx_indoors_steam_vent_weak"] = loadfx("vfx/moments/mp_zerosub/vfx_indoors_steam_vent_weak");
  level._effect["vfx_light_warning_red"] = loadfx("vfx/moments/mp_zerosub/vfx_light_warning_red");
  level._effect["vfx_snow_drift_roofline"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_roofline");
  level._effect["vfx_snow_edgeblow_m"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_edgeblow_m");
  level._effect["vfx_indoors_steam_vent"] = loadfx("vfx/moments/mp_zerosub/vfx_indoors_steam_vent");
  level._effect["vfx_indoors_steam"] = loadfx("vfx/moments/mp_zerosub/vfx_indoors_steam");
  level._effect["vfx_snow_drift_twirlingonly"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_twirlingonly");
  level._effect["vfx_snow_drift_s"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_s");
  level._effect["vfx_playercentric_indoors"] = loadfx("vfx/moments/mp_zerosub/vfx_playercentric_indoors");
  level._effect["vfx_snow_drift_wall_heavy"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_wall_heavy");
  level._effect["vfx_snow_drift_unevengrnd"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_unevengrnd");
  level._effect["vfx_snow_drift_thickwflakes"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_thickwflakes");
  level._effect["vfx_snow_drift_wall"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_wall");
  level._effect["vfx_snow_clouding_m"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_clouding_m");
  level._effect["vfx_snow_drift_l"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift_l");
  level._effect["vfx_meltzone_steam_s"] = loadfx("vfx/moments/mp_zerosub/vfx_meltzone_steam_s");
  level._effect["vfx_yeti_frost_scr"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_frost_scr");
  level._effect["vfx_yeti_breath_scr"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_breath_scr");
  level._effect["vfx_yeti_snow_scr"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_snow_scr");
  level._effect["vfx_snow_roofswirl_m"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_roofswirl_m");
  level._effect["vfx_melt_dripping1"] = loadfx("vfx/moments/mp_zerosub/vfx_melt_dripping1");
  level._effect["vfx_meltzone_steam"] = loadfx("vfx/moments/mp_zerosub/vfx_meltzone_steam");
  level._effect["vfx_snow_drift"] = loadfx("vfx/moments/mp_zerosub/vfx_snow_drift");
  level._effect["vfx_playercentric_snowamb"] = loadfx("vfx/moments/mp_zerosub/vfx_playercentric_snowamb");
  level._effect["vfx_yeti_shadow_scr"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_shadow_scr");
  level._effect["vfx_yeti_snowcover"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_snowcover");
  level._effect["vfx_yeti_snowcover_scr"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_snowcover_scr");
  level._effect["vfx_blood_explosion"] = loadfx("vfx/moments/mp_zerosub/vfx_blood_explosion");
  level._effect["vfx_yeti_snowcover_upflip"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_snowcover_upflip");
  level._effect["vfx_yeti_snowcover_dissolve"] = loadfx("vfx/moments/mp_zerosub/vfx_yeti_snowcover_dissolve");
  level.tv_info = spawnStruct();
  level._effect["tv_explode"] = loadfx("fx/explosions/tv_flatscreen_explosion");
  level._effect["tv_hockey"][1] = loadfx("vfx/moments/mp_zerosub/video_hockey_play1");
  level._effect["tv_hockey"][2] = loadfx("vfx/moments/mp_zerosub/video_hockey_play2");
  level._effect["tv_hockey"][3] = loadfx("vfx/moments/mp_zerosub/video_hockey_promo");
  level.tv_info.effectlength["tv_hockey"][1] = 4.45;
  level.tv_info.effectlength["tv_hockey"][2] = 6.4;
  level.tv_info.effectlength["tv_hockey"][3] = 9.6;
  level.tv_info.tag["tv_hockey"] = "tag_fx";
  level.tv_info.destroymodel["tv_hockey"] = "tv_flatscreen_large_d";
  level._effect["tv_hockey_scale1pt5"][1] = loadfx("vfx/moments/mp_zerosub/video_hockey_play1_scale1pt5");
  level._effect["tv_hockey_scale1pt5"][2] = loadfx("vfx/moments/mp_zerosub/video_hockey_play2_scale1pt5");
  level._effect["tv_hockey_scale1pt5"][3] = loadfx("vfx/moments/mp_zerosub/video_hockey_promo_scale1pt5");
  level.tv_info.effectlength["tv_hockey_scale1pt5"][1] = 4.45;
  level.tv_info.effectlength["tv_hockey_scale1pt5"][2] = 6.4;
  level.tv_info.effectlength["tv_hockey_scale1pt5"][3] = 9.6;
  level.tv_info.tag["tv_hockey_scale1pt5"] = "tag_fx_scale1pt5";
  level.tv_info.destroymodel["tv_hockey_scale1pt5"] = "tv_flatscreen_large_scale1pt5_d";
}